In [1]:
import numpy as np
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])
D = np.array([0.1, 0.3])

for name,array in zip(list('ABCD'),[A,B,C,D]):
    print(f"{name}:{np.all(array)}")

A: True
B: False
C: False
D: True


In [1]:
import numpy as np

A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])

for name,value in zip(list('ABC'),[A,B,C]):
    print(f"{name}: {np.all(value,axis=1)}")

A: [ True  True]
B: [ True False]
C: [False  True]


In [5]:
import numpy as np
A = np.array([[0, 0, 0],
              [0, 0, 0]])
B = np.array([[0, 0, 0],
              [0, 1, 0]])
C = np.array([[False, False, False],
              [True, False, False]])
D = np.array([[0.1, 0.0]])

for name,value in zip(list('ABCD'),[A,B,C,D]):
    print(f"{name}: {np.any(value)}")

A: False
B: True
C: True
D: True


In [3]:
import numpy as np
A = np.array([[0, 0, 0],
              [0, 0, 0]])
B = np.array([[0, 0, 0],
              [0, 1, 0]])
C = np.array([[False, False, False],
              [True, False, False]])
D = np.array([[0.1, 0.0]])

for name, value in zip(list('ABCD'),[A,B,C,D]):
    print(f"{name}: {np.any(value,axis=0)}")

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


In [4]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [6]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
print(np.allclose(A,B))

True


In [10]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

comparision=(A==B)
print(comparision)

# other way
print(np.equal(A,B))

[False False  True]
[False False  True]


In [15]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
# way 1
greater_A=np.where(A>B,True, False)
print(greater_A)

# way 2
print(A>B)

# way 3
print(np.greater(A,B))

[ True False False False]
[ True False False False]
[ True False False False]


In [19]:
arr=np.zeros((4,4),dtype='int')
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
arr=np.ones((10,10),dtype='int')
print(arr*255)

print("-"*50)
arr=np.full(100,255).reshape(10,10)
print(arr)

[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]
--------------------------------------------------
[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


In [26]:
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [27]:
print(np.arange(10,100).reshape(9,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [29]:
print(np.eye(6,6,dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [30]:
np.random.seed(10)
arr=np.random.rand(30)
print(arr)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


In [31]:
np.random.seed(20)
arr=np.random.randn(40).reshape(10,4)
print(arr)

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]
